src/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('schools.urls', namespace="schools")),
    url(r'^', include('quizes.urls', namespace="quizes")),
]

src/quizes/urls.py
from django.conf.urls import url

from .views import Test, Result, ManageQuiz, AllQuiz, AddQuiz


urlpatterns = [
    url(r'^quiz/(?P<quiz_id>[0-9]+)', Test.as_view(), name="quiz"),
    url(r'^result/(?P<quiz_id>[0-9]+)', Result.as_view(), name="result"),
    url(r'^quiz/$', AllQuiz.as_view(), name="all"),
    url(r'^quiz/edit/(?P<quiz_id>[0-9]+)$', ManageQuiz.as_view(), name="edit"),
    url(r'^quiz/add/$', AddQuiz.as_view(), name="add"),
]

src/schools/urls.py
from django.conf.urls import url

from .views import Home, Login, Logout, Register, Dashboard, DashboardDetail


urlpatterns = [
    url(r'^$', Home.as_view(), name="home"),
    url(r'^login/$', Login.as_view(), name="login"),
    url(r'^logout/$', Logout.as_view(), name="logout"),
    url(r'^register/$', Register.as_view(), name="register"),
    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^dashboard/(?P<quiz_id>[0-9]+)$',
        DashboardDetail.as_view(), name="dashboard-detail"),
]

src/quizes/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone


QUESTION_TYPES = (
    (1, 'Multiple Choice'),
    (2, 'Descriptive')
)


class Quiz(models.Model):
    title = models.CharField(max_length=40)

    start = models.DateTimeField()
    endtime = models.DateTimeField()

    def is_open(self):
        return self.start < timezone.now() < self.endtime

    def has_started(self):
        return self.start < timezone.now()

    def has_ended(self):
        return timezone.now() > self.endtime

    def status(self):
        if self.is_open():
            return 'Open'
        if self.has_ended():
            return 'Closed on %s' % (self.endtime.strftime("%B %d, %Y"))

        return 'Starts on %s' % (self.start.strftime("%B %d, %Y"))

    def __str__(self):
        return self.title


class Question(models.Model):
    value = models.TextField()
    q_type = models.IntegerField(choices=QUESTION_TYPES, default=1)

    in_quiz = models.ForeignKey(Quiz)

    def __str__(self):
        return self.value

    def get_answers(self):
        return self.answerchoices_set.filter(correct=True)


class AnswerChoices(models.Model):
    value = models.CharField(max_length=20)
    correct = models.BooleanField(default=False)
    to_question = models.ForeignKey(Question)

    def __str__(self):
        return self.value

src/quizes/views.py
from datetime import datetime

from django.views.generic import View
from django.template.response import TemplateResponse
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.utils.decorators import method_decorator
from django.utils import timezone

from .models import Quiz, Question, AnswerChoices
from schools.models import TestDetails


def is_admin(user):
    return user.is_authenticated() and user.profile.user_type == 'adm'


class Test(View):

    def get(self, request, quiz_id):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')

        profile = request.user.profile
        if profile.is_staff():
            return TemplateResponse(request, 'schools/test-dashboard.html')

        if profile.is_student():
            quiz = get_object_or_404(Quiz, id=quiz_id)
            if profile.has_participated(quiz):
                return TemplateResponse(
                    request,
                    'prepared/message-alert.html',
                    {'message': 'You have already participated in the quiz.'})

            return TemplateResponse(request,
                                    'quizes/quiz.html',
                                    {'quiz': quiz,
                                     'questions': quiz.question_set.all()})

        return TemplateResponse(request, 'schools/home.html')

    def post(self, request, quiz_id):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')

        profile = request.user.profile
        if profile.is_staff():
            return TemplateResponse(request, 'schools/test-dashboard.html')

        if profile.is_student():
            quiz = get_object_or_404(Quiz, id=quiz_id)
            if profile.has_participated(quiz):
                return TemplateResponse(
                    request,
                    'prepared/message-alert.html',
                    {'message': 'You have already participated in the quiz.'})

            user = request.user.profile
            try:
                test = TestDetails.objects.create(student=user, quiz=quiz)

                for question in quiz.question_set.all():
                    ans_choice = request.POST.get(
                        'for_q_%d' % (question.id), None)
                    question.testanswers_set.create(
                        test=test,
                        answer=AnswerChoices.objects.get(id=ans_choice))

                return TemplateResponse(
                    request,
                    'prepared/message-success.html',
                    {'message': 'Your answers have been saved successfully.'})
            except Exception as e:
                print '%s (%s)' % (e.message, type(e))
                if quiz is not None:
                    quiz.delete()

                return TemplateResponse(
                    request, 'quizes/add.html',
                    {'quiz': quiz,
                     'message': {'type': 'warning', 'head': 'Alert!!',
                                 'value': 'Could not save the quiz'}})


class Result(View):

    def get(self, request, quiz_id):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')

        profile = request.user.profile
        if profile.is_staff():
            return TemplateResponse(request, 'schools/test-dashboard.html')

        if profile.is_student():
            quiz = get_object_or_404(Quiz, id=quiz_id)
            if not profile.has_participated(quiz):
                return TemplateResponse(
                    request,
                    'prepared/message-alert.html',
                    {'message': 'You have not participated in the quiz yet.'})

            test = profile.testdetails_set.filter(quiz=quiz).first()
            answers = test.answers.all()
            total = test.answers.count()
            marks = len([a for a in answers if a.is_correct()])

            return TemplateResponse(request,
                                    'quizes/results.html',
                                    {'quiz': quiz,
                                     'answers': answers,
                                     'total': total,
                                     'marks': marks})

        return TemplateResponse(request, 'schools/home.html')


class AllQuiz(View):

    @method_decorator(user_passes_test(is_admin))
    def get(self, request):
        quizes = Quiz.objects.all()
        return TemplateResponse(
            request, 'quizes/manage.html', {'quizes': quizes})


class AddQuiz(View):

    @method_decorator(user_passes_test(is_admin))
    def get(self, request):
        return TemplateResponse(request, 'quizes/add.html')

    def post(self, request):
        quiz = None
        # import pdb; pdb.set_trace()

        try:
            title = request.POST['title']
            print(request.POST)
            start_date = request.POST['start_date']
            start_time = request.POST['start_time']
            end_date = request.POST['end_date']
            end_time = request.POST['end_time']

            starttime = timezone.make_aware(datetime.strptime(
                start_date + ' ' + start_time, '%Y-%m-%d %I:%M %p'))
            endtime = timezone.make_aware(datetime.strptime(
                end_date + ' ' + end_time, '%Y-%m-%d %I:%M %p'))
            quiz = Quiz.objects.create(title=title,
                                       start=starttime, endtime=endtime)

            # print(request.POST.getlist('question'))

            # questions = request.POST['question']
            i = j = 0

            q = request.POST.get('question[%d]' % (i), '')
            while q != '':
                print('Question: ' + q)
                question = Question.objects.create(
                                value=q, q_type=1, in_quiz=quiz)

                a = request.POST.get('option[%d][%d]' % (i, j), '')
                c = bool(request.POST.get('correct[%d][%d]' % (i, j), False))
                while a != '':
                    print('Answer: ' + a)
                    AnswerChoices.objects.create(
                        value=a, correct=c, to_question=question)
                    j += 1
                    a = request.POST.get('option[%d][%d]' % (i, j), '')
                    c = bool(request.POST.get('correct[%d][%d]' % (i, j),
                                              False))

                j = 0
                i += 1
                q = request.POST.get('question[%d]' % (i), '')

            # print(questions)
            # for q in questions:
            #     print(q)

            quizes = Quiz.objects.all()
            return TemplateResponse(
                request, 'quizes/manage.html',
                {'message': {'type': 'success', 'head': 'Success!!',
                             'value': 'Quiz saved successfully'},
                 'quizes': quizes})

        except Exception as e:
            print '%s (%s)' % (e.message, type(e))
            if quiz is not None:
                quiz.delete()

            return TemplateResponse(
                request, 'quizes/add.html',
                {'message': {'type': 'warning', 'head': 'Alert!!',
                             'value': 'Could not save the quiz'}})


class ManageQuiz(View):

    @method_decorator(user_passes_test(is_admin))
    def get(self, request, quiz_id):
        quiz = get_object_or_404(Quiz, id=quiz_id)
        return TemplateResponse(
            request, 'quizes/manage-quiz.html', {'quiz': quiz})

    @method_decorator(user_passes_test(is_admin))
    def post(self, request):
        pass

src/quizes/templates/quizes/add.html
{% extends "layouts/default.html" %}
{% load static %}

{% block content %}
<div ng-controller="AddQuizController as vm">
    <form method="POST" action="{% url 'quizes:add' %}">
        {% csrf_token %}
        {% verbatim %}
        <div class="form-group">
            <label for="title">Title</label>
            <input type="text" name="title" ng-model="title" class="form-control input-lg" id="title" placeholder="Quiz title">
        </div>
        <div class="row">
            <div class="col col-sm-6">
                <div class="row">
                    <div class="col col-sm-6">
                        <div class="form-group">
                            <label for="title">Start date time</label>
                            <p class="input-group">
                                <input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="vm.startdate" is-open="vm.startdatepicker.opened" datepicker-options="vm.dateOptions" ng-required="true" close-text="Close" alt-input-formats="altInputFormats" name="start_date" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" ng-click="vm.openStart()"><i class="glyphicon glyphicon-calendar"></i></button>
                                </span>
                            </p>
                        </div>
                    </div>
                    <div class="col col-sm-6">
                        <div class="form-group">
                            <div uib-timepicker ng-model="vm.startTime"></div>
                            <input type="hidden" ng-model="vm.startTime" name="start_time" value="{{vm.startTime | date:'shortTime' }}">
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-sm-6">
                <div class="row">
                    <div class="col col-sm-6">
                        <div class="form-group">
                            <label for="title">End date time</label>
                            <p class="input-group">
                                <input type="text" class="form-control" uib-datepicker-popup="{{format}}" ng-model="vm.endtime" is-open="vm.enddatepicker.opened" datepicker-options="vm.dateOptions" ng-required="true" close-text="Close" alt-input-formats="altInputFormats" name="end_date" />
                                <span class="input-group-btn">
                                    <button type="button" class="btn btn-default" ng-click="vm.openEnd()"><i class="glyphicon glyphicon-calendar"></i></button>
                                </span>
                            </p>
                        </div>  
                    </div>
                    <div class="row">
                        <div class="col col-sm-6">
                            <div class="form-group">
                                <div uib-timepicker ng-model="vm.endTime"></div>
                                <input type="hidden" ng-model="vm.endTime" name="end_time" value="{{vm.endTime | date:'shortTime' }}">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col col-sm-12">
                <div class="row"  ng-repeat="question in vm.questions">
                    <div class="col col-sm-10">
                        <div class="text-left">
                            <div class="row">
                                <div class="col col-sm-12">
                                    <div class="form-group">
                                        <label for="question_{{$index}}">Question</label>
                                        <input type="text" name="question[{{$index}}]" class="form-control" id="question_{{$index}}" placeholder="Question" ng-model="question.value">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-sm-offset-1 col-sm-6" ng-repeat="option in question.options">
                                    <div class="form-group">
                                        <label for="option_{{$parent.$index}}_{{$index}}">Option</label>
                                        <input name="option[{{$parent.$index}}][{{$index}}]"" type="text" class="form-control" id="option_{{$index}}" placeholder="Question" ng-model="option.value">
                                    </div>
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="correct[{{$parent.$index}}][{{$index}}]" ng-model="option.correct"> Correct answer
                                        </label>
                                    </div>
                                    <div ng-if="$last">
                                        <div class="btn btn-primary" ng-click="vm.addOption(question)" >
                                        Add option
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                <div class="text-right">
                    <button class="btn btn-primary" type="button" ng-click="vm.addQuestion()">
                        Add question
                    </button>
                </div>
            </div>
        </div>

        <button type="submit" class="btn btn-primary">
            Submit
        </button>
        {% endverbatim %}
    </form>
</div>
{% endblock %}


{% block scriptsAppend %}
    <script type="text/javascript" src="{% static 'js/add-quiz.js' %}" ></script>
{% endblock %}

src/quizes/templates/quizes/admin-dashboard.html
{% extends "layouts/default.html" %}

{% block content %}
    <table class="table table-striped">
        <thead> 
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th class="text-right">Participated</th>
            </tr>
        </thead>
    {% for quiz in quizes %}
        <tr>
            <td>{{quiz.title}}</td>
            <td>{{quiz.status}}</td>
            <td class="text-right">
                {{ quiz.testdetails_set.count }}
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

src/quizes/templates/quizes/manage.html
{% extends "layouts/default.html" %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th></th>
            </tr>
        </thead>
    {% for quiz in quizes %}
        <tr>
            <td>{{quiz.title}}</td>
            <td>{{quiz.status}}</td>
            <td class="text-right">
                {% if not quiz.has_started %}
                <a class="btn btn-primary btn-sm" href="{% url 'quizes:add' %}">
                    Manage
                </a>
                {% endif %}

                <a class="btn btn-primary btn-sm" href="">
                    See dashboard
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

src/quizes/templates/quizes/quiz.html
{% extends "layouts/default.html" %}

{% block content %}
    <h3>{{quiz.title}}</h3>

    <h4>Answer the following questions</h4>
    <form method="POST">
        {% csrf_token %}
        {% for question in questions %}
        <h5>Q. {{question.value}} </h5>
        <div>
            {% for option in question.answerchoices_set.all %}
            <div class="radio">
                <label>
                    <input type="radio" name="for_q_{{question.id}}" value="{{option.id}}">
                    {{option.value}}
                </label>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">
            Submit
        </button>
    </form>
{% endblock %}

src/quizes/templates/quizes/results.html
{% extends "layouts/default.html" %}

{% block content %}
    <h3>{{quiz.title}}</h3>

    {% for answer in answers %}
    <h5>Q. {{answer.question.value}} </h5>
    <div>
        <strong>Actual answer: </strong> {{ answer.question.get_answers.0.value }}
    </div>
    <div>
        <strong>Your answer: </strong> {{ answer.answer.value }}
    </div>
    <div>
        <strong>Result: </strong>
        {% if answer.is_correct %}
            <span class="text-success">
                Right answer <span class="glyphicon glyphicon-ok-sign"></span>
            </span>
        {% else %}
            <span class="text-danger">
                Wrong answer <span class="glyphicon glyphicon-remove-sign"></span>
            </span>
        {% endif %}
    </div>
    {% endfor %}
    <hr>
    <div>
        <strong>Total questions: </strong> {{total}}
    </div>
    <div>
        <strong>Result: </strong> {{marks}}/{{total}}
    </div>
{% endblock %}

src/quizes/templates/quizes/teacher-dashboard-detail.html
{% extends "layouts/default.html" %}

{% block content %}
    {% if quiz %}
        <h2>Quiz: {{quiz.title}}</h2>
        <h5><strong>Status: </strong>{{quiz.status}}</h5>
    {% endif %}
    {% if data and data|length > 0 %}
        <table class="table table-striped">
            <thead> 
                <tr>
                    <th>Student</th>
                    <th class="text-right">Participated</th>
                </tr>
            </thead>
        {% for item in data %}
            <tr>
                <td>{{item.student.login.username}}</td>
                <td class="text-right">
                    {% if item.participated %}
                        <span class="text-success">
                            Participated <span class="glyphicon glyphicon-ok-sign"></span>
                        </span>
                    {% else %}
                        <span class="text-danger">
                            Not participated <span class="glyphicon glyphicon-remove-sign"></span>
                        </span>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </table>
    {% endif %}
{% endblock %}

src/quizes/templates/quizes/teacher-dashboard.html
{% extends "layouts/default.html" %}

{% block content %}
    <table class="table table-striped">
        <thead> 
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th class="text-right">Total students participated</th>
                <th class="text-right">Your students particpated</th>
                <th></th>
            </tr>
        </thead>
    {% for item in data %}
        <tr>
            <td>{{item.quiz.title}}</td>
            <td>{{item.quiz.status}}</td>
            <td class="text-right">
                {{ item.quiz.testdetails_set.count }}
            </td>
            <td class="text-right">
                {{ item.count }}
            </td>
            <td>
                <a type="button" class="btn btn-primary" href="{% url 'schools:dashboard-detail' item.quiz.id %}">
                    View details
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}