src/project/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('schools.urls', namespace="schools")),
    url(r'^', include('quizes.urls', namespace="quizes")),
]

src/quizes/urls.py
from django.conf.urls import url

from .views import Test, Result, ManageQuiz, AllQuiz, AddQuiz


urlpatterns = [
    url(r'^quiz/(?P<quiz_id>[0-9]+)', Test.as_view(), name="quiz"),
    url(r'^result/(?P<quiz_id>[0-9]+)', Result.as_view(), name="result"),
    url(r'^quiz/$', AllQuiz.as_view(), name="all"),
    url(r'^quiz/edit/(?P<quiz_id>[0-9]+)$', ManageQuiz.as_view(), name="edit"),
    url(r'^quiz/add/$', AddQuiz.as_view(), name="add"),
]

src/schools/urls.py
from django.conf.urls import url

from .views import Home, Login, Logout, Register, Dashboard, DashboardDetail


urlpatterns = [
    url(r'^$', Home.as_view(), name="home"),
    url(r'^login/$', Login.as_view(), name="login"),
    url(r'^logout/$', Logout.as_view(), name="logout"),
    url(r'^register/$', Register.as_view(), name="register"),
    url(r'^dashboard/$', Dashboard.as_view(), name="dashboard"),
    url(r'^dashboard/(?P<quiz_id>[0-9]+)$',
        DashboardDetail.as_view(), name="dashboard-detail"),
]

src/schools/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from quizes.models import Quiz, Question, AnswerChoices


CITY_CHOICES = (
    ('hyd', 'Hyderabad'),
    ('mum', 'Mumbai'),
    ('del', 'Delhi'),
    ('ban', 'Banglore')
)

USER_TYPE = (
    ('adm', 'Admin'),
    ('staff', 'Staff'),
    ('stud', 'Student')
)


class School(models.Model):
    name = models.CharField(max_length=40)

    city = models.CharField(max_length=40, choices=CITY_CHOICES)

    def __str__(self):
        return '%s, %s' % (self.name, self.city)


class Profile(models.Model):
    login = models.OneToOneField(User)
    in_school = models.ForeignKey(School, null=True)
    user_type = models.CharField(max_length=10, choices=USER_TYPE)
    standard = models.IntegerField(null=True)

    tests = models.ManyToManyField(Quiz, through='TestDetails')

    # def save(self, *args, **kwargs):
    #     self.login = User.objects.create_user(
    #         username=kwargs['username'], password=kwargs['password'])
    #     # self.user_type = 'staff'
    #     # self.in_school = kwargs['in_school']
    #     return super(Profile, self).save(*args, **kwargs)

    def __str__(self):
        return '%s: %s' % (self.user_type, self.login.username)

    def is_staff(self):
        return self.user_type == 'staff'

    def is_student(self):
        return self.user_type == 'stud'

    def is_admin(self):
        return self.user_type == 'adm'

    def has_participated(self, quiz):
        return self.testdetails_set.filter(quiz=quiz).first() is not None

# class Staff(models.Model):
#     login = models.OneToOneField(User)

#     in_school = models.ForeignKey(School)

#     def save(self, *args, **kwargs):
#         group = Group.objects.filter(name='staff').first()
#         if group is None:
#             group = Group.objects.create(name='staff')

#         user = super(Staff, self).save(*args, **kwargs)
#         user.groups.add(group)
#         return user

#     def __str__(self):
#         return 'Staff: %s' % (self.login.username)


# class Student(models.Model):
#     login = models.OneToOneField(User)

#     in_school = models.ForeignKey(School)
#     standard = models.IntegerField()

#     tests = models.ManyToManyField(Quiz, through='TestDetails')

#     def save(self, *args, **kwargs):
#         group = Group.objects.filter(name='student').first()
#         if group is None:
#             group = Group.objects.create(name='student')

#         user = super(Student, self).save(*args, **kwargs)
#         user.groups.add(group)
#         return user

#     def __str__(self):
#         return 'Student: %s, standard: %s' % (self.login.username,
#                                               self.standard)


class TestDetails(models.Model):
    student = models.ForeignKey(Profile)
    quiz = models.ForeignKey(Quiz)

    max_marks = models.IntegerField(null=True)
    score = models.IntegerField(null=True)

    # answers = models.ManyToManyField('TestAnswers')

    def __str__(self):
        return '[Student: %s, Quiz: %s]' % (self.student, self.quiz)


class TestAnswers(models.Model):
    test = models.ForeignKey(TestDetails, related_name="answers")
    question = models.ForeignKey(Question)
    answer = models.ForeignKey(AnswerChoices, null=True)

    def is_correct(self):
        return self.answer in self.question.answerchoices_set.filter(
            correct=True)

    def __str__(self):
        return '[Test: %s, Q: %s, A: %s]' % (
            self.test, self.question, self.answer)

src/schools/views.py
from django.views.generic import View
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.shortcuts import get_object_or_404

from quizes.models import Quiz
from .models import School, Profile


class Home(View):
    def get(self, request):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')

        profile = request.user.profile
        if profile.is_admin():
            url = reverse('quizes:all')
            return HttpResponseRedirect(url)
        if profile.is_staff():
            url = reverse('schools:dashboard')
            return HttpResponseRedirect(url)
        if profile.is_student():
            quizes = Quiz.objects.all()
            print(quizes)
            return TemplateResponse(request,
                                    'schools/quizes.html',
                                    {'quizes': quizes})

        return TemplateResponse(request, 'schools/home.html')


class Login(View):
    def get(self, request):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')
        return HttpResponseRedirect('/')

    def post(self, request):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/')

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)

        if user and user.is_active:
            login(request, user)
            return HttpResponseRedirect('/')

        return TemplateResponse(request, 'schools/login-reg.html')


class Logout(View):
    def get(self, request):
        logout(request)
        return HttpResponseRedirect('/')


class Register(View):
    def get(self, request):
        if not request.user.is_authenticated():
            schools = School.objects.all()
            return TemplateResponse(request, 'schools/registration.html', {
                'schools': schools
                })
        return HttpResponseRedirect('/')

    def post(self, request):
        if request.user.is_authenticated():
            return HttpResponseRedirect('/')

        username = request.POST['username']
        password = request.POST['password']

        user = User.objects.create_user(username=username, password=password)
        standard = 0
        try:
            standard = int(float(request.POST.get('standard', '0')))
        except Exception:
            pass

        Profile.objects.create(
            login=user,
            user_type=request.POST['user_type'],
            in_school=School.objects.get(id=request.POST['school']),
            standard=standard)

        return TemplateResponse(request, 'schools/login-reg.html')


class Dashboard(View):
    def get(self, request):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')

        profile = request.user.profile
        if profile.is_admin():
            quizes = Quiz.objects.all()
            return TemplateResponse(request, 'quizes/admin-dashboard.html',
                                    {'quizes': quizes})

        if profile.is_staff():
            quizes = Quiz.objects.all()
            school = profile.in_school
            data = []

            for q in quizes:
                item = {}
                item['quiz'] = q
                item['count'] = q.testdetails_set.filter(
                    student__in_school=school).count()
                data.append(item)

            return TemplateResponse(request, 'quizes/teacher-dashboard.html',
                                    {'data': data})


class DashboardDetail(View):
    def get(self, request, quiz_id):
        if not request.user.is_authenticated():
            return TemplateResponse(request, 'schools/login-reg.html')

        profile = request.user.profile
        if profile.is_staff():
            school = profile.in_school
            try:
                # print(quiz_id)
                quiz = get_object_or_404(Quiz, id=quiz_id)
                data = []
                tests = quiz.testdetails_set.filter(
                    student__in_school=school)

                for test in tests:
                    # print(test.student)
                    item = {}
                    item['student'] = test.student
                    item['participated'] = test.student.has_participated(quiz)
                    data.append(item)

                return TemplateResponse(
                    request, 'quizes/teacher-dashboard-detail.html',
                    {'quiz': quiz, 'data': data})

            except Exception as e:
                print '%s (%s)' % (e.message, type(e))

                return TemplateResponse(
                    request, 'quizes/teacher-dashboard-detail.html',
                    {'data': [],
                     'message': {'type': 'warning', 'head': 'Alert!!',
                                 'value': 'Could not get details'}})

src/schools/templates/schools/dashboard.html
{% extends "layouts/default.html" %}

{% block content %}
Dashboard {{request.user}}
{% endblock %}

src/schools/templates/schools/home.html
{% extends "layouts/default.html" %}

{% block content %}
Hello {{request.user}}
{% endblock %}

src/schools/templates/schools/login-reg.html
{% extends "layouts/default.html" %}

{% block content %}
    <div class="col col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">Login</div>
            <div class="panel-body">
                <form method="POST" action="{% url 'schools:login' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-default">login</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/schools/templates/schools/quizes.html
{% extends "layouts/default.html" %}

{% block content %}
    <table class="table table-striped">
        <thead> 
            <tr>
                <th>Title</th>
                <th>Status</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
    {% for quiz in quizes %}
        <tr>
            <td>{{quiz.title}}</td>
            <td>{{quiz.status}}</td>
            <td class="text-right">
                {% if quiz.is_open %}
                <a class="btn btn-primary btn-sm" href="{% url 'quizes:quiz' quiz.id %}">
                    Participate            
                </a>
                {% endif %}
            </td>
            <td class="text-right">
                <a class="btn btn-primary btn-sm" href="{% url 'quizes:result' quiz.id %}">
                    See result            
                </a>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock %}

src/schools/templates/schools/registration.html
{% extends "layouts/default.html" %}

{% block content %}
    <div class="col col-md-6 col-md-offset-3">
        <div class="panel panel-primary">
            <div class="panel-heading">Login</div>
            <div class="panel-body">
                <form method="POST" action="{% url 'schools:register' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username">Username</label>
                        <input type="text" class="form-control" name="username" id="username" placeholder="Username">
                    </div>
                    <div class="form-group">
                        <label for="password">Password</label>
                        <input type="password" class="form-control" name="password" id="password" placeholder="Password">
                    </div>
                    <div class="form-group">
                        <label for="re-password">Re-enter password</label>
                        <input type="password" class="form-control" name="re-password" id="re-password" placeholder="Re-enter password">
                    </div>
                    <div class="form-group">
                        <label>Account type</label>
                        <select name="user_type" class="form-control">
                            <option  value="staff">Staff</option>
                            <option value="stud">Student</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Select school</label>
                        <select name="school" class="form-control">
                            {% for school in schools %}
                            <option value="{{school.id}}">{{school.name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="username">Standard</label>
                        <input type="number" class="form-control" name="standard" id="standard" placeholder="Standard">
                        (for students only)
                    </div>
                    <button type="submit" class="btn btn-primary">Register</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}